'use strict';
const $ = id => document.getElementById(id);
let token='', analysis='', current=null, refs=[], library=[], models=[], dirty=false, timer=null, activeJob=null;
const roles=['bg','surface','primary','secondary','accent','text','muted'];
const initialPalette=['#171F39','#263152','#82A6FF','#D29BEF','#F6A35D','#F2F5FF','#A6B2CE'];
function node(tag,text,attrs={}) { const e=document.createElement(tag); if(text!==null)e.textContent=text; Object.assign(e,attrs); return e; }
function toast(message) { $('toast').textContent=message; $('toast').hidden=false; clearTimeout(toast.t); toast.t=setTimeout(()=>$('toast').hidden=true,6000); }
async function api(path,options={}) {
  const headers={'X-Studio-Token':token,...options.headers};
  if(options.body && !(options.body instanceof FormData)) {headers['Content-Type']='application/json'; options.body=JSON.stringify(options.body);}
  const response=await fetch(path,{...options,headers}); const data=await response.json();
  if(!response.ok)throw new Error(data.error || 'Request failed'); return data;
}
function action(id,fn) {$(id).addEventListener('click',async()=>{const b=$(id); b.disabled=true; try {await fn();}catch(e){toast(e.message);}finally{b.disabled=false;}});}
function markDirty(){dirty=true; $('version').textContent=current?`Version ${current.version} · unsaved changes`:'Unsaved';}
function palette(values){$('palette').replaceChildren(); roles.forEach((role,i)=>{const wrap=node('div',null),label=node('label',role,{htmlFor:'color-'+role}),c=node('input',null,{type:'color',id:'color-'+role,value:values[role]||initialPalette[i]}),hex=node('input',null,{type:'text',value:c.value.toUpperCase(),maxLength:7});hex.setAttribute('aria-label',role+' hex code'); c.oninput=()=>{hex.value=c.value.toUpperCase();markDirty();};hex.onchange=()=>{if(/^#[\da-f]{6}$/i.test(hex.value)){c.value=hex.value;markDirty();}else{toast('Use a six-digit hex color, e.g. #355BE2');hex.value=c.value;}};wrap.append(c,label,hex);$('palette').append(wrap);});}
function payload(){return {analysis,name:$('name').value,brief:$('brief').value,direction:$('direction').value,avoid:$('avoid').value,palette:Object.fromEntries(roles.map(r=>[r,$('color-'+r).value])),fonts:{heading:$('heading-font').value,body:$('body-font').value},website:$('website').value,references:refs.map(r=>r.id),version:current?.version};}
function typePreview(){$('type-heading').style.fontFamily=`"${$('heading-font').value}", sans-serif`;$('type-body').style.fontFamily=`"${$('body-font').value}", sans-serif`;}
function populate(t){analysis=t.analysis||'';$('analysis-status').textContent=analysis||'Suggestions are editable. Your saved choices stay fixed across batches.';['name','brief','direction','avoid','website'].forEach(k=>$(k).value=t[k]||'');palette(t.palette);$('heading-font').value=t.fonts.heading;$('body-font').value=t.fonts.body;typePreview();$('contrast').textContent=t.contrast?`Text/background contrast ${t.contrast.textOnBackground}:1 · Muted/background ${t.contrast.mutedOnBackground}:1. Aim for 4.5:1 for normal text.`:'';}
function drawLibrary(){ $('theme-list').replaceChildren(); if(!library.length)$('theme-list').append(node('p','Your saved themes will live here.',{className:'hint'}));library.forEach(t=>{const b=node('button',t.name,{className:current?.id===t.id?'active':''}),colors=node('span',null,{className:'mini-colors'});['primary','secondary','accent'].forEach(k=>{const c=node('i',null);c.style.background=t.palette[k];colors.append(c);});b.append(colors);b.onclick=()=>loadTheme(t.id).catch(e=>toast(e.message));$('theme-list').append(b);});}
function drawRefs(){ $('references').replaceChildren();$('ref-count').textContent=`${refs.length} / 8`;refs.forEach(r=>{const card=node('article',null,{className:'ref'});if(r.kind==='image')card.append(node('img',null,{src:r.url,alt:r.name,loading:'lazy'}));card.append(node('p',r.name+' · '+r.role));if(r.notes)card.append(node('p',r.notes));if(r.palette.length){const b=node('button','Use these colors');b.onclick=()=>{const p=payload().palette;['primary','secondary','accent'].forEach((k,i)=>p[k]=r.palette[i%r.palette.length]);palette(p);markDirty();toast('Reference colors applied to primary, secondary and accent.');};card.append(b);}if(r.text){const b=node('button','Read guidelines');b.onclick=()=>showText(r.name,r.text);card.append(b);}const remove=node('button','Remove');remove.onclick=()=>{refs=refs.filter(x=>x.id!==r.id);drawRefs();markDirty();};card.append(remove);$('references').append(card);});}
async function loadTheme(id){if(dirty&&!confirm('Discard unsaved edits and open this theme?'))return;clearTimeout(timer);activeJob=null;const data=await api('/api/themes/'+id);current=data.theme;refs=data.references;populate(current);dirty=false;$('version').textContent='Version '+current.version;$('page-title').textContent=current.name;$('page-subtitle').textContent='Your saved direction, ready for the next collection.';$('breadcrumb').textContent='Your workspace / '+current.name;$('export').disabled=false;drawRefs();drawLibrary();drawAssets(data.assets);drawHistory(data.versions);const j=data.jobs.find(j=>['queued','running'].includes(j.status));if(j)watch(j.id);else{$('job-status').textContent='';$('cancel').hidden=true;}}
async function saveTheme(){if(current&&!dirty)return current;const t=await api(current?'/api/themes/'+current.id:'/api/themes',{method:current?'PUT':'POST',body:payload()});current=t;dirty=false;library=[t,...library.filter(x=>x.id!==t.id)];await loadTheme(t.id);toast('Theme saved.');return t;}
function drawHistory(versions){$('history').replaceChildren();versions.forEach(v=>{const row=node('div',null,{className:'history-row'});row.append(node('span',`Version ${v.version} · ${new Date(v.updated*1000).toLocaleDateString()}`));const b=node('button','Restore as new version');b.onclick=async()=>{try{await api(`/api/themes/${current.id}/restore/${v.id}`,{method:'POST',body:{}});dirty=false;await loadTheme(current.id);toast('Version restored as a new revision.');}catch(e){toast(e.message);}};row.append(b);$('history').append(row);});}
function drawAssets(assets){$('asset-count').textContent=`${assets.length} images`;if(!assets.length){$('gallery').innerHTML=emptyHTML;return;}$('gallery').replaceChildren();assets.forEach(a=>{const card=node('article',null,{className:'asset'});card.append(node('img',null,{src:a.url,alt:`${a.kind==='procedural'?'Procedural graphic':'Generated image'} for ${a.snapshot.name}`,loading:'lazy'}));const info=node('div',null,{className:'asset-info'});info.append(node('p',`${a.provider} · ${a.quality||'draft'} · v${a.theme_version} · ${a.width} × ${a.height}\nSeed ${a.seed}`));const buttons=node('div',null,{className:'asset-actions'});buttons.append(node('a','Download',{href:a.url+'?download=1',download:a.path}),node('a','WebP',{href:a.url+'?web=1',download:''}),node('a','Clean PNG',{href:a.url+'?clean=1',download:''}));if(a.svg)buttons.append(node('a','SVG',{href:a.svg+'?download=1',download:''}));const details=node('button','Details');details.onclick=()=>showText('Image details · Clean PNG removes file metadata, not pixel watermarks',JSON.stringify({provider:a.provider,model:a.model,themeVersion:a.theme_version,seed:a.seed,prompt:a.prompt,referenceMode:a.reference_mode,attempts:a.attempts},null,2));const regen=node('button','New variation');regen.onclick=async()=>{regen.disabled=true;try{const j=await api('/api/assets/'+a.id+'/regenerate',{method:'POST',body:{seed:Math.floor(Math.random()*2147483646),chain:chain(),quality:$('quality').value}});watch(j.id);}catch(e){toast(e.message);}finally{regen.disabled=false;}};buttons.append(details,regen);info.append(buttons);card.append(info);$('gallery').append(card);});}
function chain(){return $('engine').value==='auto'?models.map(p=>p.id):[$('engine').value];}
function showText(title,text){$('modal-title').textContent=title;$('modal-body').replaceChildren();const pre=node('pre',text),copy=node('button','Copy prompt / details',{className:'primary'});copy.onclick=async()=>{try{await navigator.clipboard.writeText(text);toast('Copied.');}catch{toast('Clipboard unavailable. Select and copy the text.');}};$('modal-body').append(copy,pre);$('modal').showModal();}
async function watch(jid){clearTimeout(timer);activeJob=jid;try{const job=await api('/api/jobs/'+jid);if(activeJob!==jid)return;$('job-status').replaceChildren(node('p',job.message));const progress=node('progress',null,{max:job.count,value:job.completed});progress.setAttribute('aria-label','Batch progress');$('job-status').append(progress);const live=['queued','running'].includes(job.status);$('cancel').hidden=!live;if(job.failures.length){const b=node('button','View failed attempts');b.onclick=()=>showText('Provider attempts',JSON.stringify(job.failures,null,2));$('job-status').append(b);}if(current?.id===job.theme_id){const data=await api('/api/themes/'+current.id);drawAssets(data.assets);}if(live)timer=setTimeout(()=>watch(jid),1800);else{activeJob=null;toast(job.message);}}catch(e){toast(e.message);activeJob=null;$('cancel').hidden=true;}}
const emptyHTML=$('gallery').innerHTML;
action('new-theme',async()=>{if(dirty&&!confirm('Discard unsaved edits?'))return;clearTimeout(timer);current=null;refs=[];dirty=false;activeJob=null;populate({palette:Object.fromEntries(roles.map((r,i)=>[r,initialPalette[i]])),fonts:{heading:'Space Grotesk',body:'DM Sans'},avoid:'unrequested text, logos, visual clutter, inconsistent style'});$('page-title').textContent='Give your ideas a visual home.';$('page-subtitle').textContent='Gather references, shape a theme, then build a collection.';$('breadcrumb').textContent='Your workspace / New theme';$('version').textContent='Unsaved';$('export').disabled=true;$('job-status').textContent='';$('cancel').hidden=true;$('history').replaceChildren(node('p','Save a theme to keep its first version.',{className:'hint'}));drawAssets([]);drawRefs();drawLibrary();});
action('draft',async()=>{const t=await api('/api/draft',{method:'POST',body:{brief:$('brief').value,name:$('name').value||$('brief').value.slice(0,50),references:refs.map(r=>r.id)}});t.website=$('website').value;populate(t);markDirty();toast(t.analysis_attempts?.length?'AI analysis unavailable; an editable offline draft was used.':'Direction suggested. Review it before saving.');});
action('save',saveTheme);
action('generate',async()=>{const t=await saveTheme();const [width,height]=$('size').value.split('x').map(Number);const j=await api('/api/themes/'+t.id+'/jobs',{method:'POST',body:{count:Number($('count').value),width,height,seed:Number($('seed').value),chain:chain(),quality:$('quality').value,reference_mode:$('reference-mode').value}});watch(j.id);});
action('cancel',async()=>{if(activeJob)await api('/api/jobs/'+activeJob+'/cancel',{method:'POST',body:{}});toast('Stop requested. Current image work may need time to finish.');});
action('export',async()=>{const t=await saveTheme();location.href='/api/themes/'+t.id+'/export';});
action('web-prompt',async()=>{const t=await saveTheme();const result=await api('/api/themes/'+t.id+'/web-prompt');showText('Your website design prompt',result.prompt);});
action('providers-open',async()=>{const info=await api('/api/bootstrap');models=info.providers;$('modal-title').textContent='Models & connection status';$('modal-body').replaceChildren(node('p','Cloud connections are opt-in. No credentials are stored in your theme or browser. Hosted free quotas can run out; model availability varies.',{className:'hint'}));models.forEach(p=>{const item=node('section',null,{className:'provider'});item.append(node('h3',p.name+(p.ready?(p.kind==='cloudflare'||p.kind==='hf'?' · Configured (not live-verified)':' · Ready offline'):' · Setup needed')),node('p',p.cost),node('p','License: '+p.license),node('p',p.setup));if(p.url)item.append(node('a','Model documentation',{href:p.url,target:'_blank',rel:'noreferrer'}));$('modal-body').append(item);});$('modal').showModal();});
$('modal-close').onclick=()=>$('modal').close();
$('reference-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(refs.length>=8)throw new Error('Use up to eight references per theme');const data=new FormData();data.append('file',f);data.append('role',$('reference-role').value);data.append('notes',$('reference-notes').value);const r=await api('/api/references',{method:'POST',body:data});refs.push(r);drawRefs();markDirty();toast('Reference saved on this computer.');}catch(err){toast(err.message);}finally{e.target.value='';}};
['name','brief','direction','avoid','website','heading-font','body-font'].forEach(k=>$(k).addEventListener('input',()=>{markDirty();typePreview();}));
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{const data=await api('/api/bootstrap');token=data.token;library=data.themes;models=data.providers;$('profile').textContent=data.profile;['heading-font','body-font'].forEach(id=>data.fonts.forEach(f=>$(id).append(node('option',f,{value:f}))));models.forEach(p=>$('engine').append(node('option',p.name+(p.ready?'':' · setup needed'),{value:p.id})));palette({});$('body-font').value='DM Sans';drawLibrary();if(library.length)await loadTheme(library[0].id);}catch(e){toast(e.message);}})();

$('import-art').onclick=()=>$('art-file').click();
$('art-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const t=await saveTheme();const data=new FormData();data.append('file',file);data.append('source','External image imported by user');await api('/api/themes/'+t.id+'/import',{method:'POST',body:data});await loadTheme(t.id);toast('Image added. Original file metadata is retained; Clean PNG is available separately.');}catch(err){toast(err.message);}finally{e.target.value='';}};
